name: workflow
on:
  push:
  pull_request:
jobs:
  workflow:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
      - name: Upgrade
        run: |
          yarn install
          yarn up
      - name: Lint
        run: yarn fixlint
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull && git commit -am "Updated packages and submodules" && git push || echo "Done"
      - name: Build
        run: yarn build
      - name: Deploy to GitHub Pages
        run: |
          cd ./.vuepress/dist
          git init
          git add --all
          git checkout --orphan gh-pages
          git commit --allow-empty --message "Deploy to GitHub pages"
          git push --force ***github.com/2asa/2asa.github.io.git gh-pages
